using UnityEngine;
public enum Paintings : byte // All colors form Eden
{
    Unpainted,

    LightRed,
    LightOrange,
    LightYellow,
    LightGreen,
    LightCyan,
    LightBlue,
    LightPurple,
    LightPink,
    LightGray_White,

    MediumLightRed,
    MediumLightOrange,
    MediumLightYellow,
    MediumLightGreen,
    MediumLightCyan,
    MediumLightBlue,
    MediumLightPurple,
    MediumLightPink,
    MediumLightGray,

    Red,
    Orange,
    Yellow,
    Green,
    Cyan,
    Blue,
    Purple,
    Pink,
    Gray,

    MediumDarkRed,
    MediumDarkOrange,
    MediumDarkYellow,
    MediumDarkGreen,
    MediumDarkCyan,
    MediumDarkBlue,
    MediumDarkPurple,
    MediumDarkPink,
    MediumDarkGray,

    DarkRed,
    DarkOrange,
    DarkYellow,
    DarkGreen,
    DarkCyan,
    DarkBlue,
    DarkPurple,
    DarkPink,
    DarkGray,

    VeryDarkRed,
    VeryDarkOrange,
    VeryDarkYellow,
    VeryDarkGreen,
    VeryDarkCyan,
    VeryDarkBlue,
    VeryDarkPurple,
    VeryDarkPink,
    VeryDarkGray_Black,
}